i = input("enter file number");
[f,p] = uigetfile({'*.png;*.jpg;*.bmp;*.tif','Supported images';...
                 '*.png','Portable Network Graphics (*.png)';...
                 '*.jpg','J-PEG (*.jpg)';...
                 '*.bmp','Bitmap (*.bmp)';...
                 '*.tif','Tagged Image File (*.tif,)';...
                 '*.*','All files (*.*)'});
rgb = imread([p f]);

[f,p] = uigetfile({'*.png;*.jpg;*.bmp;*.tif','Supported images';...
                 '*.png','Portable Network Graphics (*.png)';...
                 '*.jpg','J-PEG (*.jpg)';...
                 '*.bmp','Bitmap (*.bmp)';...
                 '*.tif','Tagged Image File (*.tif,)';...
                 '*.*','All files (*.*)'});
thermal = imread([p f]);

cpselect(rgb, thermal);
a = 'image_registration_matricies/mytform_' ;
b = num2str(i) ;
c = '.mat' ;
file_name = [a b c];
mytform = fitgeotrans(movingPoints, fixedPoints, 'affine');
save(file_name, 'mytform');

