
[f,p] = uigetfile({'*.png;*.jpg; *.jpeg, *.bmp;*.tif','Supported images';...
                 '*.png','Portable Network Graphics (*.png)';...
                 '*.jpg','J-PEG (*.jpg)';...
                 '*.jpeg','J-PEG (*.jpeg)';...
                 '*.bmp','Bitmap (*.bmp)';...
                 '*.tif','Tagged Image File (*.tif,)';...
                 '*.*','All files (*.*)'});

             
rgb = imread([p f]);

[f,p] = uigetfile({'*.png;*.jpg; *.jpeg, *.bmp;*.tif','Supported images';...
                 '*.png','Portable Network Graphics (*.png)';...
                 '*.jpg','J-PEG (*.jpg)';...
                 '*.jpeg','J-PEG (*.jpeg)';...
                 '*.bmp','Bitmap (*.bmp)';...
                 '*.tif','Tagged Image File (*.tif,)';...
                 '*.*','All files (*.*)'});

thermal = imread([p f]);

load('image_registration_matricies/final_transformation.mat');

mytform = t2;

Roriginal = imref2d(size(thermal));
registered = imwarp(rgb, mytform, 'OutputView',Roriginal);
%imshow(registered)
imshowpair(thermal, registered, 'blend')